// This file is generated by Prismic local builder. Update with care!

export { default as BriefLetter } from "./BriefLetter";
export { default as ImageHero } from "./ImageHero";
export { default as InfoCard } from "./InfoCard";
export { default as NewsletterForm } from "./NewsletterForm";
export { default as SimpleSpacer } from "./SimpleSpacer";
export { default as SimpleText } from "./SimpleText";
export { default as TextImage } from "./TextImage";
